### ISSUE TITLE
Correctly Position Input Boxes| Importance * * * *

### ISSUE THREAD

**Issue by devojoyti** [markroxor/Roboism#9]
In [fill_info.py](https://github.com/markroxor/Roboism/blob/master/mainsite/templates/registration/fill_info.html), I have styled it using CSS and Django. (See styling classes [here](https://github.com/markroxor/Roboism/blob/master/mainsite/forms.py) ) I want the names and fill boxes under each other, like

Name: 
[ fill box ]

Not like

Name: [ fill box ]

Fix it ASAP

**Comment by DevilHunterr** [comment]
sir, do you want changes in login.html and want the form look like 
username:
[ input ]
password:
[ input ]

**Comment by devojoyti** [comment]
Clone the latest repo to your PC and install django to run in locally as I have instructed on readme. 

Go to login-> register you will see I have already styled them. But after you fill register, a fill info form comes, which is not styled as desired. eg.I want them as - 
username:
[ input ]
password:
[ input ]

**Comment by catchashu10** [comment]
Sir, I am unable to find fill_info.py file.

**Comment by devojoyti** [comment]
Here it is -> [fill_info.html](https://github.com/markroxor/Roboism/blob/master/mainsite/templates/registration/fill_info.html)

**Comment by catchashu10** [comment]
Sir please look at the code that I have commited -> [register.html](https://github.com/markroxor/Roboism/blob/master/mainsite/templates/registration/register.html).
The form will look as desired but I think it does not goes with the backend.
I am trying to learn django to understand it.

**Comment by catchashu10** [comment]
Sir although I don't know django yet, but after searching a lot on the net. I came up with the following code to give the desired result at registeration page:

``` html
{% extends "registration/base.html" %}
{% block title %}User Registration{% endblock %}
{% block head %}User Registration{% endblock %}
{% block content %}

     <form id="register" class="w3-container" method="POST" action=".">{% csrf_token %}
        {% for field in form %}
             <div class="fieldWrapper">
               {{ field.errors }}
               {{ field.label_tag }}: {{ field }}
          </div>
        {% endfor %}
        <input class="w3-btn w3-round-xxlarge w3-blue" type="submit" value="Register" />
    </form>
{% endblock %}
```

 Please copy this code in the register.html locally and run the website locally to check.
 No changes required in forms.py

**Comment by markroxor** [comment]
@catchashu10 thanks. Fixed at [5debb87](https://github.com/markroxor/Roboism/commit/5debb87271b4b4c055a35e91710a9994c06d7dc4)

**Comment by catchashu10** [comment]
Sir fill_info.html is also not as desired . So I think this issue is still not resolved completely.
